/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\src\assets\3D\level_1.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
// @ts-ignore
import level_1 from './../../../assets/3D/level_1.glb'

export function FisrtLevel(props) {
  const { nodes, materials } = useGLTF(level_1)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.room.geometry} material={nodes.room.material} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[5.5, 0.5, 1.5]} />
      <mesh geometry={nodes.screen_3001.geometry} material={nodes.screen_3001.material} position={[4.13, 2.86, -2.17]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[4.12, 1.43, -2.86]} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[4.08, 1.19, -1.57]} />
      <mesh geometry={nodes.Export_Wires.geometry} material={nodes.Export_Wires.material} position={[4.16, 1.72, -0.03]} rotation={[1.5, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-2.5, 0.5, -1.5]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0.5, 0.5, -3.5]} />
      <mesh geometry={nodes.screen_3002.geometry} material={nodes.screen_3002.material} position={[-5.95, 2.49, 0.04]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-1.13, 0, 1.5]} />
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-0.5, 0.59, -0.5]} rotation={[Math.PI, Math.PI / 4, -1.2]} />
    </group>
  )
}

useGLTF.preload(level_1)